---
databases:
  default: ${VECTOR_DB_TYPE:-weaviate-cloud}
  vector_databases:
    # Uses the Weaviate Cloud (paid) Vector DB environment
    - name: weaviate-cloud
      openai_api_key: ${OPENAI_API_KEY}  # needed for vector embeddings
      type: weaviate-cloud
      url: ${WEAVIATE_URL}
      api_key: ${WEAVIATE_API_KEY}
      collections:
        - name: ${WEAVIATE_COLLECTION:-WeaveDocs}
          type: text
          description: Weaviate CLI text collection
        - name: ${WEAVIATE_COLLECTION_IMAGES:-WeaveImages}
          type: image
          description: Weaviate CLI image collection
        - name: ${WEAVIATE_COLLECTION_TEST:-WeaveDocs_test}
          type: text
          description: Weaviate CLI text test collection
        - name: ${WEAVIATE_COLLECTION_TEST_IMAGES:-WeaveImages_test}
          type: image
          description: Weaviate CLI image test collection

    # Uses the Weaviate (OSS) Vector DB environment
    - name: weaviate-local
      type: weaviate-local
      url: http://localhost:8080
      collections:
        - name: ${WEAVIATE_COLLECTION:-WeaveDocs}
          type: text
          description: Weaviate CLI text collection
        - name: ${WEAVIATE_COLLECTION_IMAGES:-WeaveImages}
          type: image
          description: Weaviate CLI image collection

    # Uses a fake Vector DB for fast testing purposes
    - name: mock
      simulate_embeddings: true
      type: mock
      embedding_dimension: 384
      enabled: true
      collections:
        - name: WeaveDocs
          type: text
          description: Mock text documents collection
        - name: WeaveImages
          type: image
          description: Mock image documents collection
  # Collection of known schemas
  schemas:
    - name: RagMeDocs
      schema:
        class: RagMeDocs
        vectorizer: text2vec-weaviate
        properties:
          - name: url
            datatype:
              - text
            description: the source URL of the webpage
          - name: text
            datatype:
              - text
            description: the content of the webpage
          - name: metadata
            datatype:
              - text
            description: additional metadata in JSON format
      metadata:
        id:
          type: string
        metadata:
          type: string
        text:
          type: string
        url:
          type: string
    - name: RagMeImages
      schema:
        class: RagMeImages
        vectorizer: text2vec-weaviate
        properties:
          - name: url
            datatype:
              - text
            description: the source URL or filename of the image
          - name: image
            datatype:
              - text
            description: the image reference (truncated base64 or URL)
          - name: metadata
            datatype:
              - text
            description: additional metadata in JSON format
          - name: image_data
            datatype:
              - text
            description: Weaviate auto-schema property
      metadata:
        id:
          type: string
        image:
          type: string
        image_data:
          type: string
        metadata:
          type: string
        url:
          type: string
