// SPDX-License-Identifier: MIT
// Copyright (c) 2026 dr.max

package chunking

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/maximilien/weave-cli/src/pkg/agents"
	"github.com/spf13/viper"
)

func TestScanFiles(t *testing.T) {
	root := t.TempDir()
	paths := []string{"readme.md", "notes.TXT", "config.yaml", "image.png", "nested/data.json"}
	for _, relative := range paths {
		path := filepath.Join(root, relative)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("create directory: %v", err)
		}
		if err := os.WriteFile(path, []byte("sample"), 0o600); err != nil {
			t.Fatalf("write %s: %v", relative, err)
		}
	}

	files, err := scanFiles(root, "")
	if err != nil {
		t.Fatalf("scanFiles() error: %v", err)
	}
	want := []string{
		filepath.Join(root, "config.yaml"),
		filepath.Join(root, "nested/data.json"),
		filepath.Join(root, "notes.TXT"),
		filepath.Join(root, "readme.md"),
	}
	if !reflect.DeepEqual(files, want) {
		t.Fatalf("scanFiles() = %#v, want %#v", files, want)
	}

	files, err = scanFiles(root, "*.md")
	if err != nil || !reflect.DeepEqual(files, []string{filepath.Join(root, "readme.md")}) {
		t.Fatalf("scanFiles(*.md) = %#v, %v", files, err)
	}
	if _, err := scanFiles(root, "["); err == nil {
		t.Fatal("scanFiles() accepted invalid glob")
	}
	if _, err := scanFiles(filepath.Join(root, "missing"), ""); err == nil {
		t.Fatal("scanFiles() accepted missing root")
	}
}

func TestSaveAndDisplayChunkingAnalysis(t *testing.T) {
	output := &agents.ChunkingAnalysisOutput{Confidence: 0.8}
	output.Recommendation.RecommendedSize = 800
	output.Recommendation.MinSize = 400
	output.Recommendation.MaxSize = 1200
	output.Recommendation.OverlapSize = 80
	output.Recommendation.DocumentType = "technical"
	output.Recommendation.Reasoning = "preserve sections"
	output.Recommendation.Considerations = []string{"code blocks"}
	output.Metrics.FileTypes = []string{"md"}
	output.Metrics.AvgContentLength = 1000
	output.Metrics.AvgParagraphs = 10
	output.Metrics.AvgParagraphLen = 100
	output.Metrics.ContentDensity = "medium"
	output.Warnings = []string{"small sample"}

	displayChunkingAnalysis(output)
	path := filepath.Join(t.TempDir(), "chunking.yaml")
	if err := saveChunkingToFile(output, path); err != nil {
		t.Fatalf("saveChunkingToFile() error: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read recommendations: %v", err)
	}
	if text := string(data); !strings.Contains(text, "Generated by Weave CLI") || !strings.Contains(text, "confidence: 0.8") {
		t.Fatalf("saved recommendations = %q", text)
	}
	if err := saveChunkingToFile(output, filepath.Join(t.TempDir(), "missing", "chunking.yaml")); err == nil {
		t.Fatal("saveChunkingToFile() accepted an unwritable path")
	}
}

func TestRunChunkingSuggestValidation(t *testing.T) {
	viper.Reset()
	t.Cleanup(viper.Reset)
	t.Setenv("OPENAI_API_KEY", "")

	if err := runChunkingSuggest(nil, []string{filepath.Join(t.TempDir(), "missing")}); err == nil || !strings.Contains(err.Error(), "does not exist") {
		t.Fatalf("missing source error = %v", err)
	}
	if err := runChunkingSuggest(nil, []string{t.TempDir()}); err == nil || !strings.Contains(err.Error(), "OPENAI_API_KEY") {
		t.Fatalf("missing API key error = %v", err)
	}
}
