// PM2 Ecosystem Configuration
// Generated by weave-cli from weave-stack.yaml
//
// This file configures PM2 process management for the dashboard.
// See: https://pm2.keymetrics.io/docs/usage/application-declaration/

module.exports = {
  apps: [
    {
      name: '{{ .AppName }}',
      cwd: '{{ .Cwd }}',
      script: '{{ .Script }}',
      instances: {{ .Instances }},
      autorestart: {{ .Autorestart }},
      watch: {{ .Watch }},
      max_memory_restart: '{{ .MaxMemoryRestart }}',
      env: {
        {{- range $key, $value := .Env }}
        {{ $key }}: '{{ $value }}',
        {{- end }}
      },
      error_file: '{{ .ErrorLog }}',
      out_file: '{{ .OutLog }}',
      {{- if .LogDateFormat }}
      log_date_format: '{{ .LogDateFormat }}',
      {{- end }}
      merge_logs: {{ .MergeLogs }},
      min_uptime: '{{ .MinUptime }}',
      max_restarts: {{ .MaxRestarts }},
      kill_timeout: {{ .KillTimeout }},
    },
  ],
};
